name: wrshh
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  google_maps_flutter: ^2.2.2
  google_maps_flutter_web: ^0.4.0+3
  animated_text_kit: ^4.2.2
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
#  modal_progress_hud: ^0.1.3
  modal_progress_hud_nsn: ^0.3.0
  booking_calendar: ^1.1.7
#  time_range: ^1.1.0
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  firebase_storage: ^11.0.10
  calendar_timeline: ^1.1.0
#  calendar_carousel: ^0.1.0-nullsafety.2
#  time_picker: ^0.0.2
  file_picker: ^5.2.5
#  rate_in_stars: ^0.0.3
  rate: ^0.0.1
  syncfusion_flutter_pdfviewer: ^20.4.44
  open_document: ^1.0.5
  pdf: ^3.8.4

  intl_phone_field: ^3.1.0
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/flags/
