// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAjfo8Y3ez4sifmLikGWrNGInYU6qteOg',
    appId: '1:856152766204:web:df9c56f3b52fe148b84979',
    messagingSenderId: '856152766204',
    projectId: 'wrshhx',
    authDomain: 'wrshhx.firebaseapp.com',
    databaseURL: 'https://wrshhx-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wrshhx.appspot.com',
    measurementId: 'G-N418KMQVND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDu6NWOfF9TGx3lsk2thNHy-bMiTNoZqg',
    appId: '1:856152766204:android:ece8b213a36207f7b84979',
    messagingSenderId: '856152766204',
    projectId: 'wrshhx',
    databaseURL: 'https://wrshhx-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wrshhx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMyiFux8SYN-suIj9DxihJMYZXW3yp8A8',
    appId: '1:856152766204:ios:a784d63111e0e63bb84979',
    messagingSenderId: '856152766204',
    projectId: 'wrshhx',
    databaseURL: 'https://wrshhx-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wrshhx.appspot.com',
    iosClientId: '856152766204-724ihtbn2vha26m0rn5pvae13v886f09.apps.googleusercontent.com',
    iosBundleId: 'com.example.wrshh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMyiFux8SYN-suIj9DxihJMYZXW3yp8A8',
    appId: '1:856152766204:ios:a784d63111e0e63bb84979',
    messagingSenderId: '856152766204',
    projectId: 'wrshhx',
    databaseURL: 'https://wrshhx-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wrshhx.appspot.com',
    iosClientId: '856152766204-724ihtbn2vha26m0rn5pvae13v886f09.apps.googleusercontent.com',
    iosBundleId: 'com.example.wrshh',
  );
}
